config/routes.rb
Rails.application.routes.draw do
  
  root 'sessions#new'
  get 'chatroom', to: 'chatroom#index'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true
    scope :custom_display, -> { order(:created_at).last(20) } 
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :username, presence: true, 
                         uniqueness: { case_sensitive: false }, 
                         length: { minimum: 3, maximum: 25 }
    validates :email, presence: true, 
                      uniqueness: { case_sensitive: false }, 
                      format: { with: VALID_EMAIL_REGEX }, 
                      length: { maximum: 105 }
    has_secure_password
    has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id]        
    end

    def logged_in?
        !!current_user
    end

    def require_user
        if !logged_in?
            redirect_to root_path
        end
    end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController

    before_action :require_user
   
    def index
        @message = Message.new
        @messages = Message.custom_display
    end

    private

    def set_message
        @message = Message.find(params[:id])
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

    before_action :require_user

    def create
        message = current_user.messages.build(message_params)
        if message.save
           ActionCable.server.broadcast "chatroom_channel",
                                         mod_message: message_render(message)
        end
    end

    private

    def message_params
        params.require(:message).permit(:body)
    end

    def message_render(message)
        render(partial: 'message', locals: {message: message})
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    before_action :logged_in_redirect, only: [:new, :create]

    def new
        redirect_to chatroom_path if logged_in?
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            session[:username] = user.username    
            flash[:notice] = "Logged in successfully" 
            redirect_to chatroom_path
        else
            flash.now[:alert] = "There was something wrong with your login details"
            render 'new'
        end   
    end

    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end

    private

    def logged_in_redirect

        if  logged_in?
            redirect_to chatroom_path
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :logged_in_redirect, only: [:new, :create]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            session[:username] = @user.username
            flash[:notice] = "Welcome to Realtime Chat App #{@user.username}, you have successfully signed up"
            redirect_to chatroom_path
        else
            render 'new'
        end
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def logged_in_redirect

        if  logged_in?
            redirect_to chatroom_path
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular brown coffee icon"></i>
  Real Time Chat App
</h2>
<%= render 'layouts/alert-success' %>
<div class="ui two column grid">

    <div class="twelve wide column">
        <div class="ui fluid raised card chatbox">
            <div class="content" id="messages">
               <div class="ui large feed" id="message-container">
                    <%= render @messages  %>
                </div>
            </div>
            <div class="extra content">
                <%= form_for(@message, html: {class: "ui reply form", role: "form" }, url: message_path, remote: true) do |f| %>
                    <div class="field">
                        <div class="ui fluid icon input">
                        <%= f.text_field :body,  autocomplete: "off", placeholder: "Enter a message" %>
                        <%= f.button '<i class="bordered inverted circular brown paper plane icon"></i>'.html_safe %>
                        </div>
                    </div>
                <% end %>
                
            </div>

        </div>    
    </div>

    <div class="four wide column">
            <div class="ui fluid raised card chatbox">
                <div class="content">
                    <div class="ui inverted vertical menu">
                    <a><%= link_to 'Chatroom', chatroom_path, class: "item" %></a>
                    </div>
                </div>
            </div>
    </div>
</div>

app/views/layouts/_alert-error.html.erb
<% flash.each do |name, msg| %>
<div class="ui error message">
      <i class="close icon"></i>
      <div class="header">
        <%= msg %>  
      </div>
     
</div>
<% end %>  

app/views/layouts/_alert-login-error.html.erb
<% flash.each do |name, msg| %>
<div class="ui error message">
      <i class="close icon"></i>
      <div class="header">
        <%= msg %>  
      </div>
     
</div>
<% end %>  

app/views/layouts/_alert-signup-error.html.erb
<% if obj.errors.any? %>
<div class="ui error message">
      <i class="close icon"></i>
      <div class="header">
        The following errors prevented the <%= obj.class.name.downcase %> from being saved 
      </div>
      <ul class="list">
        <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>  
      </ul>
</div>
<% end %>

app/views/layouts/_alert-success.html.erb
<% flash.each do |name, msg| %>
    <div class="ui success message">
    <i class="close icon"></i>
    <div class="header">
       <%= msg %>  
    </div>
    </div>
<% end %>  

app/views/layouts/_navigation.html.erb
<% if logged_in? %>
<a><%= link_to 'Chatroom', chatroom_path, class: "item" %></a>

<div class="right menu">
        <div class="ui dropdown item">
            Account <i class="dropdown icon"></i>
            <div class="menu">
            <a><%= link_to 'Logout', logout_path, class: "item" %></a>
            </div>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Real Time Chat App</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <div class="ui small inverted menu">
      <div class="ui container">
        <%= render 'layouts/navigation' %>
      </div>
      </div>
    <% end %>

    <div class="ui container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
    <div class="content">
    <div class="summary">
        <em style ="color: brown">
        <% if message.user.username == session[:username] %>
            <%= "Me:"  %>
        <% else  %>
            <%= message.user.username + ":" %>
        <% end  %> 
        </em><%= message.body  %>
    </div>
    </div>
</div>

app/views/users/new.html.erb
<div style="margin-top: 25px;"></div>
<h2 class="ui center aligned icon header">
  <i class="circular brown coffee icon"></i>
  Real Time Chat App
</h2>
<%= render 'layouts/alert-signup-error', obj: @user %>
<div class="ui placeholder segment">
  <div class="ui two column very relaxed stackable grid">
    <div class="column">
      <%= form_with(model: @user, html: {class: "ui form", role: "form" }, url: signup_path, local: true) do |f| %>
        <div class="ui form">
           <div class="field">
            <label>Username</label>
            <div class="ui left icon input">
              <%= f.text_field :username, placeholder: "Username" %>
              <i class="user icon"></i>
            </div>
          </div>
          <div class="field">
            <label>Email</label>
            <div class="ui left icon input">
              <%= f.email_field :email, placeholder: "Email" %>
              <i class="envelope icon"></i>
            </div>
          </div>
          <div class="field">
            <label>Password</label>
            <div class="ui left icon input">
              <%= f.password_field :password, placeholder: "Password" %>
              <i class="lock icon"></i>
            </div>
          </div>
          <%= f.submit "Sign-up", class: "ui brown fluid submit button" %>
        </div>
      <% end %>
    </div>

    <div class="middle aligned column">
      <%=  link_to root_path, style: "color:white", :action => 'Login' do %>
      <div class="ui brown big button">
        Login
      </div>
      <% end %>
    </div>
  </div>
  <div class="ui vertical divider">
    Or
  </div>
</div>